import { useState, useEffect } from "react";
import { SiteData } from "../data/sites";

const CACHE_KEY = (slug: string) => `tv_ai_review_${slug}`;

// Pre-written reviews to avoid exposing API keys client-side.
// To update: regenerate offline and paste here.
const reviews: Record<string, string> = {
  "helix-studios":
    `Helix Studios has been in the game since 2002 — founded by Keith Miller, originally in Fort Lauderdale, then San Francisco, and now based in Las Vegas. That history shows in the library: over 4,000 scenes, 2,600+ videos, and 2,354 photo galleries. It's one of the largest exclusive collections in the twink niche, period. The production values are genuinely cinematic — professional lighting, multi-camera setups, and performers with real on-screen chemistry. Newer content streams in 720p, while older material from the early years is in 480p.\n\nThe studio has expanded beyond its core site with Helix Studios Latin America (launched 2021) and Helix Studios Europe (2022), plus a narrative series called "Helix Studios Presents" available on Amazon Prime Video. Mobile streaming works well — the player is responsive and doesn't fight you with forced downloads. Navigation is clean with functional search filters, which is more than you can say for a lot of competing sites.\n\nAt $34.95/month, Helix is the most expensive site in our rankings. The annual plan drops that to $11.99/month, which is where the real value is — you get two decades of exclusive content for roughly the price of a streaming service. There's no free trial, so you're committing upfront. For fans who prioritize production quality and exclusive performers over raw volume, Helix remains the benchmark. Budget-conscious subscribers should look at the Next Door network instead.`,

  "next-door-twink":
    `Next Door Twink is the twink-specific brand within the broader Next Door Studios family, which is part of the ASGmax network. That network access is the headline feature: one membership gets you 45+ channels and over 12,500 videos. That includes Next Door Raw, Next Door Buddies, Next Door Taboo, plus external studios like Disruptive Films, Active Duty, and Pride Studios. For twink content specifically, Next Door Twink delivers well-produced scenes with natural all-American performers.\n\nVideo quality ranges from 720p to full 4K depending on when the scene was produced, and the platform supports both streaming and downloads for premium members. The mobile experience is one of the best we've tested — fast-loading pages, a smooth video player, and no intrusive pop-ups. New content drops weekly across the network, so there's always something fresh regardless of your specific preferences.\n\nAt $24.95/month for the standard plan it's reasonable pricing, but the annual plan at $10.95/month ($131.40/year) is where the value becomes hard to beat. There's also a $2.95 three-day trial for new members who want to test the platform before committing. If you want massive volume across multiple studios with solid production quality, this is the no-brainer choice in our rankings.`,

  "next-door-world":
    `Next Door World is the gateway to the full ASGmax network — 45+ channels, over 12,500 videos, and weekly new content across the entire platform. The network includes Next Door Studios' own brands (Twink, Raw, Buddies, Taboo, Originals) alongside external studios like Disruptive Films, Active Duty, and Pride Studios. Content quality varies across the network — the flagship Next Door productions are polished with strong production values, while some partner channels lean more amateur. That range is the point if you value variety.\n\nThe platform itself is well-built. Video quality spans 720p to 4K depending on the content, with adaptive streaming that adjusts to your connection. Downloads are available for premium members. Mobile optimization is solid — clean player, fast page loads, and you can filter by channel, performer, and category. The deep archive means there's a substantial back catalog to explore beyond just new releases.\n\nValue is where Next Door World dominates. At $10.95/month on the annual plan ($131.40/year), you're paying about a cent per video in the library. Even the $24.95 standard monthly price is reasonable given you're accessing 45+ channels. There's also a $2.95 three-day trial for new members. If you want maximum content for minimum spend and don't mind that not everything is twink-specific, this is objectively the best value in our entire ranking.`,

  "twinks-in-shorts":
    `Twinks in Shorts delivers exactly what the name suggests — authentic amateur-style content with real chemistry between performers. At 82/100 for content quality, you're not getting Helix-level production, but that's the point. The unscripted feel gives scenes a genuine energy that overproduced studios can't replicate. Performers look natural and comfortable, and the casual all-American vibe runs through everything.\n\nMobile works well at 85/100 — the player is responsive and streams without buffering on decent connections. Updates come at a solid 80/100 pace, keeping the library growing steadily. The site layout is straightforward, nothing fancy, but you can find what you want without digging through layers of menus.\n\nAt $29.95/month it's mid-range pricing, but the annual plan drops to $9.95/month which is genuinely cheap for the content quality. Value scores 88/100 because you're getting authentic content at a price that won't make you regret the subscription. Best suited for fans who prefer natural performers and real chemistry over polished studio productions. If that's your preference, this punches well above its price point.`,

  "athletic-twinks":
    `Athletic Twinks carves out a specific niche — toned, gym-fit performers in high-energy scenes. Content quality at 84/100 is solid. If you're into the athletic physique, the casting is on point. Scenes are well-produced with good lighting and camera work, though they don't quite reach the cinematic level of top-tier studios. The specificity of the niche is both its strength and its limitation.\n\nMobile scores 82/100 — it works without issues but doesn't feel as optimized as the larger network sites. Updates at 78/100 come regularly but not quite weekly. The library is smaller given the niche focus, which means you'll cycle through the catalog faster than on a general-purpose site.\n\nValue sits at 80/100 — the $29.95 monthly price is standard, and the $9.95 annual rate is competitive. If athletic performers are your thing, you won't find a more focused collection elsewhere. For broader tastes, a network membership like Next Door World might be better value. But for the specific audience this serves, Athletic Twinks delivers exactly what it promises without filler.`,

  "southern-strokes":
    `Southern Strokes brings a distinct all-American charm with a Southern flavor. Content quality at 78/100 is decent — performers are friendly, approachable, and feel genuinely natural on camera. The scenes prioritize authenticity over production polish, which works for the brand. You won't find dramatic lighting or multi-angle cinematography, but you will find real performers who seem to actually enjoy what they're doing.\n\nThe mobile experience at 80/100 is functional. Streaming works, navigation is simple, and the player doesn't fight you. Update frequency at 75/100 means new content arrives regularly but not as fast as the bigger studios. The library is respectable for a niche site.\n\nAt $29.95 monthly or $9.95 annually, Southern Strokes offers strong value at 90/100. That annual price makes it one of the cheapest quality options available. It's best suited for budget-conscious fans who prioritize natural performers and authentic content over high production values. If you're testing the waters or want a solid secondary subscription that won't strain your wallet, this is a smart pick.`,

  "daddy-on-twink":
    `Daddy on Twink explores intergenerational dynamics with surprisingly strong performer chemistry. Content quality at 80/100 delivers well-produced scenes that handle the age-gap dynamic tastefully. The casting does a good job of pairing performers who have genuine on-screen rapport, which elevates scenes beyond what you'd expect from a niche site.\n\nMobile comes in at 78/100 — adequate but not exceptional. The player works fine, pages load reasonably fast. Updates at 75/100 keep things moving. The site design is functional without being remarkable. You'll find what you need through basic search and category filters.\n\nPriced at $29.95 monthly or $9.95 annually, the value score of 78/100 is fair. It's not the cheapest option, but the niche is underserved enough that there aren't many alternatives. If intergenerational content is specifically what you're looking for, this is the most focused option in our rankings. Broader-taste viewers should look at network memberships instead.`,

  "touch-that-boy":
    `Touch That Boy takes a different approach — slower-paced, intimate content where the focus is on genuine connection between performers. Content quality at 79/100 reflects higher production values than typical amateur sites, with attention to mood, lighting, and pacing. If your preference leans toward sensual over intense, this hits a sweet spot that most sites in the niche completely ignore.\n\nMobile experience scores 80/100 — clean, functional, no complaints. The update frequency at 72/100 is the main weakness; new content arrives less frequently than competitors, which means the library grows slowly. If you consume content quickly, you may find yourself waiting between updates.\n\nAt $29.95 monthly or $9.95 annually, value sits at 77/100. The price is fair for what you get, but the slower updates drag the score down. Best for viewers who want quality over quantity and appreciate content where performers seem genuinely attracted to each other. It's a niche within a niche, and if it matches your taste, nothing else in our rankings comes close.`,

  "breed-me-raw":
    `Breed Me Raw doesn't sugarcoat what it offers — raw, unfiltered content with passionate performers bringing genuine intensity. Content quality at 76/100 is honest; this isn't polished cinema, it's authentic energy captured on camera. The performers are into it, and that enthusiasm translates. If you prefer real heat over glossy production, this delivers.\n\nMobile at 75/100 works but feels dated compared to the larger sites. The player streams fine, but the interface could use a refresh. Updates at 70/100 come at a steady but not rapid pace. The library is focused and specific, which keeps it from feeling bloated with filler content.\n\nAt $29.95 monthly or $9.95 annually, the value at 80/100 is solid. Part of the MyGayCash network, the site shares infrastructure with other niche brands which keeps the platform reliable. The content is very niche — if raw is your thing, this is purpose-built for you. For a broader content mix, the network memberships offer more variety at similar prices.`,

  "bareback-that-hole":
    `Bareback That Hole serves a specific audience with high-intensity raw content. Content quality at 75/100 is straightforward — the scenes are authentic and energetic, production is clean but not cinematic. The performers bring genuine enthusiasm, and the content stays consistent with what the site promises. No misleading previews here.\n\nMobile at 74/100 is functional but basic. The streaming works, but the interface feels a generation behind the more polished competitors. Updates at 70/100 are steady. The library is focused, which means less browsing and more finding what you actually came for.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is good for the niche. The annual price is affordable enough to justify as a secondary subscription alongside a larger network membership. Best suited for fans who know exactly what they want and appreciate a site that delivers it without filler. If you're exploring the category, start with a network site first and add this later if the niche appeals.`,

  "hard-brit-lads":
    `Hard Brit Lads is the go-to for British content — exclusively UK performers with that distinctive British energy. Content quality at 78/100 mixes amateur and semi-professional production. Some scenes have that polished feel while others lean into the raw charm of authentic British lads. The casting is the real draw; you won't find these performers on American sites.\n\nMobile at 76/100 is decent but not exceptional. The player works across devices, updates at 72/100 keep the catalog growing. The European audience is loyal for good reason — this is genuinely the best dedicated British option in the space.\n\nAt $29.95 monthly or $9.95 annually, value at 80/100 is fair. The annual plan makes it affordable as a niche subscription. If British performers are your preference, there's simply nothing better available. If geography doesn't matter to your preferences, the network sites offer more content for similar money. But for fans of UK content, this is essential.`,

  "prideflame":
    `Prideflame fills an important gap in the market with diverse, inclusive content celebrating Latino and mixed performers. Content quality at 74/100 is honest — production values are adequate, and the casting brings representation you won't find on most competitor sites. The authentic diversity makes it stand out in a niche that's often homogeneous.\n\nMobile at 74/100 is functional. Updates at 68/100 are the weakest point — new content arrives less frequently than competitors, which limits the library size. The site design is clean enough to navigate without frustration.\n\nAt $29.95 monthly or $9.95 annually, value at 80/100 is reasonable for the specialization. The annual price is cheap enough that it works as a supplementary subscription. Best for viewers who want representation and diversity in their content. If that matters to you — and it should — Prideflame is the only real option in the twink niche doing it consistently. The lower update frequency is a trade-off worth accepting for content you literally can't get elsewhere.`,

  "rawhole":
    `RawHole is a focused bareback site with a clear identity — raw, unfiltered scenes shot with passionate performers who actually look like they're enjoying it. Content quality at 80/100 reflects solid HD production: the lighting and angles are well-handled, but the brand prioritizes authenticity over cinematic polish. That's the right call for the niche. Casting leans toward performers with real chemistry rather than glossy studio types.\n\nMobile experience at 80/100 is genuinely good. The player streams cleanly across devices and the site doesn't push you toward downloads or out to upsell pages. Updates land at a steady 78/100 — not the fastest in the space, but enough that the library keeps growing. As part of the zBuckz network, the platform infrastructure is reliable, which matters more than people realize until a site they pay for goes down for a weekend.\n\nAt $29.95 monthly or $9.95 annually, value scores 84/100. Monthly pricing is standard for the niche — fine but not exciting — and the annual rate is where the math works. If you only watch bareback content this is a clean, focused subscription. If your tastes are broader, a network bundle gives you more variety for similar money. RawHole's strength is doing one thing well and not pretending to do anything else.`,

  "peterfever":
    `PeterFever is the leading gay Asian membership site, and it's earned that position. Content quality at 86/100 is genuinely cinematic — production values rival the top-tier general-market studios, with real attention to lighting, framing, and pacing. The casting is the headline: an exclusive roster of Asian and mixed performers you simply can't find concentrated anywhere else. The storytelling has more thought than the average gay site puts into it, which gives scenes a lift beyond the standard format.\n\nMobile at 82/100 is solid. The player is responsive, the site loads fast, and quality switching is instant. Updates at 78/100 are reliable rather than rapid — new scenes arrive regularly without the volume of network sites. As part of the zBuckz network, the platform is stable and the search/filter tools are functional. The library is substantial for a niche site.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair. The annual price puts cinematic gay Asian content in budget territory, which historically hasn't been an option. Best for fans of Asian performers who don't want to compromise on production values. If representation in your content matters, PeterFever is the most polished and consistent option available.`,

  "gayasiannetwork":
    `GayAsianNetwork is the multi-site bundle for fans of gay Asian content — one membership, multiple brands, one of the broadest Asian-focused libraries online. Content quality at 84/100 reflects the network mix: some sub-brands lean polished and studio-driven, others stay closer to amateur and authentic. That range is the appeal. You get cinematic and natural under one login rather than committing to a single style.\n\nMobile at 80/100 works without complaint. The player is reliable, navigation is straightforward, and you can filter by sub-brand to focus your browsing. Updates at 80/100 are strong — across the network, new content arrives consistently, which keeps the library feeling fresh. As part of the zBuckz infrastructure, uptime and streaming reliability are dependable.\n\nAt $29.95 monthly or $9.95 annually, value scores 88/100 — among the best in our rankings. You're getting access to multiple sites at the price of one, and the annual rate is genuinely cheap for the breadth of content. Best for anyone who wants gay Asian content without locking into a single production style. If you've been trying to decide between specific Asian sites, the network bundle is the smarter pick.`,

  "alternadudes":
    `AlternaDudes owns the alternative gay niche outright. Tattooed, pierced, scruffy performers who look nothing like the polished twinks and gym bros that dominate mainstream sites. Content quality at 80/100 leans intentionally raw — the production is clean enough to watch comfortably, but the brand resists the urge to over-polish. That's the whole point. The casting is the appeal, and over-styling would undercut it.\n\nMobile experience at 78/100 is functional. The player works, pages load reasonably, the interface gets out of the way. Updates at 76/100 come at a steady cadence — the niche audience is loyal, and the site rewards them with consistency rather than volume. Part of the zBuckz network, so the underlying platform is reliable.\n\nAt $29.95 monthly or $9.95 annually, value at 84/100 is solid. There's nothing else really like it — alt gay content is a thin space, and AlternaDudes is the dominant brand in it. If tattooed and pierced performers are your thing, this is essentially the only serious option. If they're not, this isn't the site for you, and that's fine. The brand knows exactly who it serves.`,

  "dirtyboyvideo":
    `DirtyBoyVideo is exactly what the name suggests — real, raunchy, no-frills gay content. Content quality at 76/100 is honest. You're not getting cinematic lighting or scripted scenarios. You're getting performers and authentic energy captured with adequate production. For the audience this serves, that's the right trade. Polish would feel out of place.\n\nMobile at 76/100 works without standout features. The player streams, navigation is basic, the interface is dated but functional. Updates at 74/100 are steady but not aggressive. The library is focused, which means less filler to scroll past — when you find a category you like, the catalog within it is reasonably deep. Part of the zBuckz network, with reliable streaming and stable infrastructure.\n\nAt $29.95 monthly or $9.95 annually, value at 84/100 is good. The annual price is cheap enough to work as a niche secondary subscription alongside a primary network membership. Best for fans of authentic, unfussy gay content who don't need their sites to look like Netflix. If that's you, DirtyBoyVideo delivers without pretension.`,

  "dudesraw":
    `DudesRaw is a bareback site with a real-guy aesthetic — performers who look like guys you'd actually meet rather than the polished archetypes from premium studios. Content quality at 78/100 is solid: HD throughout, clean enough production to watch comfortably, but with a deliberate energy that prioritizes chemistry over choreography. The pacing of scenes feels natural rather than staged, which is the brand's whole pitch.\n\nMobile at 78/100 is reliable. Streaming is consistent across devices, and the player doesn't fight you. Updates at 74/100 keep the library growing without flooding it. As part of the zBuckz network, the platform is stable and the search tools are functional. The library is focused on the niche, which means less time browsing irrelevant categories.\n\nAt $29.95 monthly or $9.95 annually, value at 84/100 is competitive. The annual price brings dedicated bareback content into budget territory. Best for fans who want bareback scenes with authentic performer energy rather than studio-polished talent. Pair it with a network membership for variety, or run it as a focused standalone if the niche is your main interest.`,

  "nakedsword":
    `NakedSword is the closest thing gay content has to a streaming platform with real ambition — over 50,000 scenes from more than 300 studios under one login. Content quality at 90/100 reflects both the studio breadth and the NakedSword Originals slate, which the platform produces in-house at a standard that holds up against the best specialty studios. The variety is the headline: twink, bear, muscle, fetish, bareback, romance — it's all here, with enough depth in each category that you won't burn through the relevant library quickly.\n\nThe platform itself is well-built. HD and 4K streaming work reliably, the search and filter tools are sophisticated enough to actually find specific content, and the mobile experience at 86/100 is genuinely smooth. Navigation is clean without being overwhelming given the library size. New additions arrive weekly across the partner studios and from original productions, so there's always something current. The NakedSword Originals in particular tend to be high-concept and well-cast — they're worth seeking out specifically.\n\nAt $29.95 monthly or $9.95 annually, value at 92/100 is exceptional for the breadth on offer. The monthly price is reasonable; the annual price is a steal. The only real argument against it is if you have highly specific tastes that are better served by a specialist site — but even then, NakedSword probably has enough of what you want to justify the subscription alongside a secondary niche site. For most people, this is the one subscription that covers everything.`,

  "trailertrashboys":
    `TrailerTrashBoys commits to its aesthetic more fully than almost anything else in the NakedSword Cash network — blue-collar performers, raw settings, and a gritty energy that studio-polished content genuinely cannot fake. Content quality at 80/100 isn't a measure of lighting rigs and color grading; it's a measure of whether the brand delivers what it promises, and it does. The performers are convincingly in character, and the scenes have a rough authenticity that makes the rough-trade niche actually land.\n\nStreaming is HD with a reliable mobile player at 78/100. The interface is functional rather than elegant, which is consistent with the brand's personality. Updates at 76/100 keep the library growing steadily. The back catalog has enough depth to explore without cycling through everything in a weekend. As part of the NakedSword Cash network, platform stability is solid — you won't be chasing broken links or dead embeds.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair for a specialty site that genuinely owns its niche. If rough-trade, working-class, blue-collar scenarios are your preference, this is the most committed version of that aesthetic in our rankings. If they're not, move on — the specificity that makes it great for its audience makes it completely wrong for everyone else.`,

  "japanboyz":
    `Japanboyz takes a different approach to gay Asian content than the polished studio productions on sites like PeterFever. The performers here are real guys recruited in Japan — not seasoned studio talent — which gives the scenes an authentic, nervous energy that's hard to manufacture. Content quality at 82/100 reflects solid HD production while preserving that natural feel. Lighting and angles are thoughtful without over-styling the talent into something they're not.\n\nMobile at 80/100 is clean and reliable. The player streams well, pages load quickly, and the site doesn't push you toward unnecessary upsells. Updates at 76/100 are steady — the library grows consistently, though the authentic casting approach means you won't see the volume you'd get from a factory-production site. The zBuckz infrastructure keeps things stable behind the scenes.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is solid for the niche. If you want gay Japanese content and authenticity matters more to you than studio polish, Japanboyz delivers something genuinely different from PeterFever or GayAsianNetwork. The real-guy casting is the whole point. For fans who want cinematic production over authentic energy, PeterFever is the better fit. For everyone else, Japanboyz earns its following.`,

  "sexjapantv":
    `SexJapanTV approaches Japanese gay content with a reality-TV energy — higher pacing, more dynamic camera work, and a casting approach that leans into variety rather than establishing a consistent performer roster. Content quality at 80/100 reflects solid HD production with a livelier feel than the more documentary-style Japanboyz. If you find straight-shot authentic content a bit slow, the faster-cutting, reality-inflected style here is a meaningful upgrade.\n\nMobile at 78/100 is reliable. The streaming player works well across devices, and the interface is organized well enough to browse by category or performer. Updates at 76/100 are consistent — the volume of new content is reasonable for the subscription price. Part of the zBuckz network, the infrastructure is stable and the streaming quality is predictable rather than variable.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair. If you already subscribe to Japanboyz and want more Japanese content with a different production style, this is an easy add. If you're choosing between the two, SexJapanTV rewards viewers who prefer production energy over the raw authenticity angle. The niche is narrow, but within it, the site delivers consistently.`,

  "hiroyaxxx":
    `HiroyaXXX is the dedicated solo site for Japanese performer Hiroya — a platform built specifically around one performer's content rather than a rotating cast. Content quality at 78/100 reflects careful production that frames Hiroya specifically, with scene concepts designed around his appeal rather than generic formats. If you're already a fan of his work on other sites, this is the deepest cut available: exclusive scenes, solo and duo content, and material produced specifically for this platform.\n\nMobile at 76/100 is functional. The player works across devices without issues, and the navigation is simple given the focused scope. Updates at 72/100 are slower than multi-performer sites by nature — solo performer sites release content at the pace one person can produce rather than a full studio rotation. The library is growing but compact compared to network sites.\n\nAt $29.95 monthly or $9.95 annually, this is a specialty subscription by design. Value at 80/100 is reasonable if Hiroya specifically is your reason for subscribing. For fans of his work, the exclusive content you can't find anywhere else justifies the annual price without much hesitation. For everyone else, a broader zBuckz or Asian-network site gives more total content for the same investment. Know which camp you're in before subscribing.`,

  "yoshikawasakixxx":
    `Yoshi Kawasaki is one of the most recognized names in gay adult content internationally, and his official site reflects the care you'd expect from a performer who understands his own brand. Content quality at 84/100 is high — scenes are produced with deliberate framing, real concept work, and the kind of attention to detail that comes from someone who's been in front of cameras long enough to know exactly what works. The mix of solo content, duo scenes, and behind-the-scenes material gives the site more texture than typical performer sites.\n\nMobile at 80/100 is solid. The player is reliable, the site is clean, and discovery is straightforward. Updates at 76/100 come regularly given that content production runs alongside Yoshi's broader industry work. The exclusive content is the appeal — scenes here don't appear on network releases or major studio productions.\n\nAt $29.95 monthly or $9.95 annually, value at 80/100 is fair for a performer-specific site with genuine exclusivity. The annual rate is low enough that for an established fan, this is a no-brainer. For someone less familiar with his work, start with a major studio release featuring him and use that as a litmus test before subscribing. But for the audience this serves, there's nothing else quite like it.`,

  "wuboyz":
    `WuBoyz focuses specifically on gay content featuring Chinese performers — a sub-niche within the broader Asian gay space that even dedicated networks like GayAsianNetwork don't always represent with depth. Content quality at 78/100 is solid HD with a casting approach that prioritizes diversity of Chinese performer types over any single aesthetic. The production is clean without over-polishing the talent.\n\nMobile at 78/100 works without complaint. The streaming player is reliable, pages load predictably, and navigation is simple. Updates at 74/100 are steady — the niche limits the pace of content production compared to general-market sites, but the library grows consistently. The zBuckz network infrastructure means the platform is stable and the streaming quality is dependable.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair. This is a specialty subscription for a specific preference, and within that preference it's the most focused option available. If Chinese performers specifically are your interest, WuBoyz fills a real gap that other sites including the broader Asian networks don't adequately cover. If Asian content more generally is your interest, GayAsianNetwork gives you more total breadth at the same annual price.`,

  "barebackrtxxx":
    `Bareback RT XXX delivers on its promise without theatrics — raw bareback content shot with a gritty, no-gloss aesthetic. Content quality at 76/100 is honest. The production doesn't try to compete with studio-polished sites, and that's the correct call for the brand. What it delivers is uninhibited energy captured on camera without the artifice of scripted storylines or overlit sets. Performers bring real heat, and the scenes feel genuinely unscripted.\n\nMobile at 76/100 is functional. The player streams without issues, navigation is basic, and the interface does the job without getting in the way. Updates at 72/100 are steady but not aggressive. The library is focused, and the content stays consistent with the brand's identity throughout. Part of the zBuckz network, the platform is reliable.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is solid for the niche. The annual price is the right entry point — monthly is standard but doesn't represent meaningful savings. If raw bareback content is what you're specifically looking for and you want it with a gritty rather than glossy aesthetic, this delivers without compromise. For broader tastes, pair it with a network membership that covers the rest.`,

  "cumpigmen":
    `Cum Pig Men is not for casual viewers. The content is fetish-forward, intense, and deliberately not mainstream — scenes built around cumshot and pig-play fetishes with performers who are clearly into the material they're shooting. Content quality at 78/100 reflects solid HD production with lighting and angles that serve the specific content rather than generic scene formats. This is a site that knows its audience and makes no concessions to anyone outside of it.\n\nMobile at 76/100 is functional. The player streams reliably, the interface is straightforward, updates at 74/100 are consistent. The zBuckz network backing means stable infrastructure behind the scenes. The library is focused and deep within its niche — fans who've been looking for content in this specific lane will find more here than anywhere else in our rankings.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is good for a fetish specialty site. The annual price is low enough to justify if this is content you actively seek out. If you're new to the niche and not sure, the monthly plan is the better test before committing to a year. For the audience this serves — people who know exactly what they want and find it undersupplied everywhere else — Cum Pig Men is the best option available.`,

  "realmenfuck":
    `Real Men Fuck is built around one idea: masculine performers, confident energy, no pretence. Content quality at 80/100 reflects that clarity — scenes are shot to highlight the performers rather than layer them in narrative scaffolding. The casting prioritizes men who bring genuine dominance and confidence rather than performed masculinity, and the difference is noticeable. Production is clean HD without being overproduced.\n\nMobile at 78/100 is solid. The player streams well, the interface is functional, and the site doesn't pad the experience with unnecessary upsells or pop-ups. Updates at 76/100 are steady — the library grows at a pace that makes sense for a site focused on quality casting rather than volume production. Part of the zBuckz network, the infrastructure is reliable.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair. If masculine, no-nonsense gay content with genuine dominant energy is what you're looking for, this is the most focused version of that in our rankings. The annual price makes it a reasonable standalone or complementary subscription to a broader network membership. For fans of overly scripted or polished studio content, the straight-to-the-point approach might feel sparse — but that's the brand's strength, not a weakness.`,

  "swinginballs":
    `Swingin Balls takes a lighter approach to gay content than most sites in the space — higher energy, playful scenarios, and performers who seem to be genuinely having fun. Content quality at 76/100 reflects solid HD production with a looser, more casual feel than the dramatic-tension taboo sites or clinical bareback productions. There's a personality here that the more serious niche sites lack, and for viewers who find relentlessly intense content exhausting, that's a real differentiator.\n\nMobile at 76/100 is functional. Streaming works reliably, pages load without drama, and the interface is uncomplicated. Updates at 72/100 are steady. The library is moderate in size and consistent in tone — you know what you're getting from scene to scene. Part of the zBuckz network, the underlying platform is dependable.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is good for a site that fills a genuine gap. Most gay content swings between intense fetish and heavy taboo roleplay. Swingin Balls is neither — it's just fun, energetic sex with performers who seem like they're enjoying themselves. For viewers who want that without the theatrics, the annual price makes this an easy pick as a secondary subscription.`,

  "squirtstudios":
    `Squirt Studios serves a specific fetish with genuine depth — content built around intensity, release, and performers who are specifically selected for their enthusiasm for this material. Content quality at 78/100 reflects solid HD production with framing designed around the specific fetish rather than generic scene formats. This isn't incidental content; it's curated. If this is what you're looking for, the library is more substantial than you'd find on general-market sites that treat it as a subcategory.\n\nMobile at 76/100 is reliable. The player streams consistently, navigation is straightforward, and updates at 74/100 arrive steadily. The zBuckz network backing means the platform is stable and the streaming quality is predictable. The library is focused rather than broad — if the specific content type is your interest, the depth is there. If you're testing the category, the monthly plan gives you a fair window to assess.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is reasonable for a specialty site with genuine niche depth. The annual price is low enough that for committed fans of the content type, there's no real argument against it. For casual curiosity, start with monthly. The site knows what it is and delivers it consistently, which is more than a lot of niche sites can say.`,

  "aussiesdoit":
    `Aussies Do It fills a gap that US and European studios almost entirely ignore: gay content with genuine Australian character. The performers are Australian, the locations often reflect it — outdoor settings, natural light, and a laid-back energy that you genuinely can't fake with American or British talent doing accents. Content quality at 80/100 reflects good HD production that leans into the natural-light aesthetic rather than fighting it with studio lighting setups that would undercut the brand's whole point.\n\nMobile at 78/100 is solid. The player streams reliably, pages load well, and navigation is clean. Updates at 74/100 are steady for a geographically-constrained casting pool — the site grows the library at a realistic pace rather than overpromising and flooding the catalog with filler. Part of the zBuckz network, the infrastructure is dependable and streaming quality is consistent.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is fair for what is genuinely a unique geographic niche. If Australian performers and the aesthetics that come with them are part of what you're after, this is the only serious dedicated option available. The annual price is low enough that it works well as a complementary subscription alongside a broader network membership. For viewers who don't have a strong preference for geography, the larger network sites offer more total content — but none of them offer this.`,
};

export function useAIReview(site: SiteData) {
  const [content, setContent] = useState<string>("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Check sessionStorage cache first
    const cached = sessionStorage.getItem(CACHE_KEY(site.slug));
    if (cached) {
      setContent(cached);
      return;
    }

    // Use pre-written review
    const review = reviews[site.slug];
    if (review) {
      setLoading(true);
      // Small delay to avoid layout flash
      const timer = setTimeout(() => {
        sessionStorage.setItem(CACHE_KEY(site.slug), review);
        setContent(review);
        setLoading(false);
      }, 300);
      return () => clearTimeout(timer);
    }

    // Fallback to site description
    setContent(site.description);
  }, [site.slug, site.description]);

  return { content, loading };
}
