import { useState, useEffect } from "react";
import { SiteData } from "../data/sites";

const CACHE_KEY = (slug: string) => `tv_ai_review_${slug}`;

// Pre-written reviews to avoid exposing API keys client-side.
// To update: regenerate offline and paste here.
const reviews: Record<string, string> = {
  "helix-studios":
    `Helix Studios has been in the game since 2002 — founded by Keith Miller, originally in Fort Lauderdale, then San Francisco, and now based in Las Vegas. That history shows in the library: over 4,000 scenes, 2,600+ videos, and 2,354 photo galleries. It's one of the largest exclusive collections in the twink niche, period. The production values are genuinely cinematic — professional lighting, multi-camera setups, and performers with real on-screen chemistry. Newer content streams in 720p, while older material from the early years is in 480p.\n\nThe studio has expanded beyond its core site with Helix Studios Latin America (launched 2021) and Helix Studios Europe (2022), plus a narrative series called "Helix Studios Presents" available on Amazon Prime Video. Mobile streaming works well — the player is responsive and doesn't fight you with forced downloads. Navigation is clean with functional search filters, which is more than you can say for a lot of competing sites.\n\nAt $34.95/month, Helix is the most expensive site in our rankings. The annual plan drops that to $11.99/month, which is where the real value is — you get two decades of exclusive content for roughly the price of a streaming service. There's no free trial, so you're committing upfront. For fans who prioritize production quality and exclusive performers over raw volume, Helix remains the benchmark. Budget-conscious subscribers should look at the Next Door network instead.`,

  "next-door-twink":
    `Next Door Twink is the twink-specific brand within the broader Next Door Studios family, which is part of the ASGmax network. That network access is the headline feature: one membership gets you 85 channels and over 13,000 videos. That includes Next Door Raw, Next Door Buddies, Next Door Taboo, plus external studios like Disruptive Films, Active Duty, and Pride Studios. For twink content specifically, Next Door Twink delivers well-produced scenes with natural all-American performers.\n\nVideo quality ranges from 720p to full 4K depending on when the scene was produced, and the platform supports both streaming and downloads for premium members. The mobile experience is one of the best we've tested — fast-loading pages, a smooth video player, and no intrusive pop-ups. New content drops weekly across the network, so there's always something fresh regardless of your specific preferences.\n\nAt $29.95/month it's standard pricing, but the annual plan at $7.95/month ($95.40/year) is where the value becomes hard to beat. That's 85 channels and 13,000+ videos for less than the price of a single Netflix subscription. There's no confirmed free trial currently available, though ASGmax occasionally runs promotional deals for new members. If you want massive volume across multiple studios with solid production quality, this is the no-brainer choice in our rankings.`,

  "next-door-world":
    `Next Door World is the gateway to the full ASGmax network — 85 channels, over 13,000 videos, and weekly new content across the entire platform. The network includes Next Door Studios' own brands (Twink, Raw, Buddies, Taboo, Originals) alongside external studios like Disruptive Films, Active Duty, and Pride Studios. Content quality varies across the network — the flagship Next Door productions are polished with strong production values, while some partner channels lean more amateur. That range is the point if you value variety.\n\nThe platform itself is well-built. Video quality spans 720p to 4K depending on the content, with adaptive streaming that adjusts to your connection. Downloads are available for premium members. Mobile optimization is solid — clean player, fast page loads, and you can filter by channel, performer, and category. The 20+ year archive means there's a deep back catalog to explore beyond just new releases.\n\nValue is where Next Door World dominates. At $7.95/month on the annual plan ($95.40/year), you're paying less than a cent per video in the library. Even the $29.95 monthly price is reasonable given you're accessing 85 channels. There's also a $199.95 lifetime option if you want permanent access. No free trial is currently confirmed, though seasonal promotions pop up. If you want maximum content for minimum spend and don't mind that not everything is twink-specific, this is objectively the best value in our entire ranking.`,

  "twinks-in-shorts":
    `Twinks in Shorts delivers exactly what the name suggests — authentic amateur-style content with real chemistry between performers. At 82/100 for content quality, you're not getting Helix-level production, but that's the point. The unscripted feel gives scenes a genuine energy that overproduced studios can't replicate. Performers look natural and comfortable, and the casual all-American vibe runs through everything.\n\nMobile works well at 85/100 — the player is responsive and streams without buffering on decent connections. Updates come at a solid 80/100 pace, keeping the library growing steadily. The site layout is straightforward, nothing fancy, but you can find what you want without digging through layers of menus.\n\nAt $29.95/month it's mid-range pricing, but the annual plan drops to $9.95/month which is genuinely cheap for the content quality. Value scores 88/100 because you're getting authentic content at a price that won't make you regret the subscription. Best suited for fans who prefer natural performers and real chemistry over polished studio productions. If that's your preference, this punches well above its price point.`,

  "athletic-twinks":
    `Athletic Twinks carves out a specific niche — toned, gym-fit performers in high-energy scenes. Content quality at 84/100 is solid. If you're into the athletic physique, the casting is on point. Scenes are well-produced with good lighting and camera work, though they don't quite reach the cinematic level of top-tier studios. The specificity of the niche is both its strength and its limitation.\n\nMobile scores 82/100 — it works without issues but doesn't feel as optimized as the larger network sites. Updates at 78/100 come regularly but not quite weekly. The library is smaller given the niche focus, which means you'll cycle through the catalog faster than on a general-purpose site.\n\nValue sits at 80/100 — the $29.95 monthly price is standard, and the $9.95 annual rate is competitive. If athletic performers are your thing, you won't find a more focused collection elsewhere. For broader tastes, a network membership like Next Door World might be better value. But for the specific audience this serves, Athletic Twinks delivers exactly what it promises without filler.`,

  "southern-strokes":
    `Southern Strokes brings a distinct all-American charm with a Southern flavor. Content quality at 78/100 is decent — performers are friendly, approachable, and feel genuinely natural on camera. The scenes prioritize authenticity over production polish, which works for the brand. You won't find dramatic lighting or multi-angle cinematography, but you will find real performers who seem to actually enjoy what they're doing.\n\nThe mobile experience at 80/100 is functional. Streaming works, navigation is simple, and the player doesn't fight you. Update frequency at 75/100 means new content arrives regularly but not as fast as the bigger studios. The library is respectable for a niche site.\n\nAt $29.95 monthly or $9.95 annually, Southern Strokes offers strong value at 90/100. That annual price makes it one of the cheapest quality options available. It's best suited for budget-conscious fans who prioritize natural performers and authentic content over high production values. If you're testing the waters or want a solid secondary subscription that won't strain your wallet, this is a smart pick.`,

  "daddy-on-twink":
    `Daddy on Twink explores intergenerational dynamics with surprisingly strong performer chemistry. Content quality at 80/100 delivers well-produced scenes that handle the age-gap dynamic tastefully. The casting does a good job of pairing performers who have genuine on-screen rapport, which elevates scenes beyond what you'd expect from a niche site.\n\nMobile comes in at 78/100 — adequate but not exceptional. The player works fine, pages load reasonably fast. Updates at 75/100 keep things moving. The site design is functional without being remarkable. You'll find what you need through basic search and category filters.\n\nPriced at $29.95 monthly or $9.95 annually, the value score of 78/100 is fair. It's not the cheapest option, but the niche is underserved enough that there aren't many alternatives. If intergenerational content is specifically what you're looking for, this is the most focused option in our rankings. Broader-taste viewers should look at network memberships instead.`,

  "touch-that-boy":
    `Touch That Boy takes a different approach — slower-paced, intimate content where the focus is on genuine connection between performers. Content quality at 79/100 reflects higher production values than typical amateur sites, with attention to mood, lighting, and pacing. If your preference leans toward sensual over intense, this hits a sweet spot that most sites in the niche completely ignore.\n\nMobile experience scores 80/100 — clean, functional, no complaints. The update frequency at 72/100 is the main weakness; new content arrives less frequently than competitors, which means the library grows slowly. If you consume content quickly, you may find yourself waiting between updates.\n\nAt $29.95 monthly or $9.95 annually, value sits at 77/100. The price is fair for what you get, but the slower updates drag the score down. Best for viewers who want quality over quantity and appreciate content where performers seem genuinely attracted to each other. It's a niche within a niche, and if it matches your taste, nothing else in our rankings comes close.`,

  "breed-me-raw":
    `Breed Me Raw doesn't sugarcoat what it offers — raw, unfiltered content with passionate performers bringing genuine intensity. Content quality at 76/100 is honest; this isn't polished cinema, it's authentic energy captured on camera. The performers are into it, and that enthusiasm translates. If you prefer real heat over glossy production, this delivers.\n\nMobile at 75/100 works but feels dated compared to the larger sites. The player streams fine, but the interface could use a refresh. Updates at 70/100 come at a steady but not rapid pace. The library is focused and specific, which keeps it from feeling bloated with filler content.\n\nAt $29.95 monthly or $9.95 annually with a free 2-day trial, the value at 80/100 is solid. That trial lets you see exactly what you're getting before committing. The content is very niche — if raw is your thing, this is purpose-built for you. If you're unsure, start with the trial. For a broader content mix, the network memberships offer more variety at similar prices.`,

  "bareback-that-hole":
    `Bareback That Hole serves a specific audience with high-intensity raw content. Content quality at 75/100 is straightforward — the scenes are authentic and energetic, production is clean but not cinematic. The performers bring genuine enthusiasm, and the content stays consistent with what the site promises. No misleading previews here.\n\nMobile at 74/100 is functional but basic. The streaming works, but the interface feels a generation behind the more polished competitors. Updates at 70/100 are steady. The library is focused, which means less browsing and more finding what you actually came for.\n\nAt $29.95 monthly or $9.95 annually, value at 82/100 is good for the niche. The annual price is affordable enough to justify as a secondary subscription alongside a larger network membership. Best suited for fans who know exactly what they want and appreciate a site that delivers it without filler. If you're exploring the category, start with a network site first and add this later if the niche appeals.`,

  "hard-brit-lads":
    `Hard Brit Lads is the go-to for British content — exclusively UK performers with that distinctive British energy. Content quality at 78/100 mixes amateur and semi-professional production. Some scenes have that polished feel while others lean into the raw charm of authentic British lads. The casting is the real draw; you won't find these performers on American sites.\n\nMobile at 76/100 is decent but not exceptional. The player works across devices, updates at 72/100 keep the catalog growing. The European audience is loyal for good reason — this is genuinely the best dedicated British option in the space.\n\nAt $29.95 monthly or $9.95 annually, value at 80/100 is fair. The annual plan makes it affordable as a niche subscription. If British performers are your preference, there's simply nothing better available. If geography doesn't matter to your preferences, the network sites offer more content for similar money. But for fans of UK content, this is essential.`,

  "prideflame":
    `Prideflame fills an important gap in the market with diverse, inclusive content celebrating Latino and mixed performers. Content quality at 74/100 is honest — production values are adequate, and the casting brings representation you won't find on most competitor sites. The authentic diversity makes it stand out in a niche that's often homogeneous.\n\nMobile at 74/100 is functional. Updates at 68/100 are the weakest point — new content arrives less frequently than competitors, which limits the library size. The site design is clean enough to navigate without frustration.\n\nAt $29.95 monthly or $9.95 annually, value at 80/100 is reasonable for the specialization. The annual price is cheap enough that it works as a supplementary subscription. Best for viewers who want representation and diversity in their content. If that matters to you — and it should — Prideflame is the only real option in the twink niche doing it consistently. The lower update frequency is a trade-off worth accepting for content you literally can't get elsewhere.`,
};

export function useAIReview(site: SiteData) {
  const [content, setContent] = useState<string>("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Check sessionStorage cache first
    const cached = sessionStorage.getItem(CACHE_KEY(site.slug));
    if (cached) {
      setContent(cached);
      return;
    }

    // Use pre-written review
    const review = reviews[site.slug];
    if (review) {
      setLoading(true);
      // Small delay to avoid layout flash
      const timer = setTimeout(() => {
        sessionStorage.setItem(CACHE_KEY(site.slug), review);
        setContent(review);
        setLoading(false);
      }, 300);
      return () => clearTimeout(timer);
    }

    // Fallback to site description
    setContent(site.description);
  }, [site.slug, site.description]);

  return { content, loading };
}
