-- Content log for autonomous content engine.
-- Records every page generated by scripts/generate-daily-content.ts.
CREATE TABLE IF NOT EXISTS content_log (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text NOT NULL,
  content_type text NOT NULL,
  page_title text,
  published_at timestamptz DEFAULT now(),
  word_count integer,
  affiliate_network text,
  affiliate_url_present boolean DEFAULT false,
  target_keyword text,
  meta_description_length integer,
  faq_count integer,
  internal_links_added integer,
  build_passed boolean DEFAULT false,
  git_commit_hash text,
  google_ping_success boolean,
  bing_ping_success boolean,
  error_message text
);

CREATE INDEX IF NOT EXISTS idx_content_log_published_at
  ON content_log(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_log_content_type
  ON content_log(content_type);
CREATE INDEX IF NOT EXISTS idx_content_log_slug
  ON content_log(slug);

-- Allow anon insert (script writes via VITE_SUPABASE_ANON_KEY).
ALTER TABLE content_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon insert content_log" ON content_log;
CREATE POLICY "anon insert content_log"
  ON content_log
  FOR INSERT
  TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "anon read content_log" ON content_log;
CREATE POLICY "anon read content_log"
  ON content_log
  FOR SELECT
  TO anon
  USING (true);
