/**
 * Structured comparison pairs auto-generated by `scripts/generate-comparison-pages.ts`.
 * Each entry encodes which sites are paired, the niche overlap that drove the
 * pairing, and a suggested winner / runner-up so ComparePage can render a
 * deterministic verdict without recomputing on every render.
 *
 * Regenerate with:
 *   npx tsx scripts/generate-comparison-pages.ts
 */

export interface ComparisonPair {
  /** URL slug fragment: `${a}-vs-${b}` (sorted alphabetically for canonicalisation) */
  slug: string;
  siteA: string;
  siteB: string;
  /** Niche shared by both sites — drives the pairing and the niche-internal-link block */
  primaryNiche: string | null;
  /** Slug of the suggested overall winner (higher score) */
  suggestedWinner: string;
  /** Slug of the runner-up (cheaper of the two on annual) */
  suggestedRunnerUp: string;
  /** Search-volume priority hint, 1 (low) – 5 (top); pairs with priority >= 4 are surfaced as "Popular Comparisons" */
  priority: number;
}

export const comparisonPairs: ComparisonPair[] = [
  {
    "slug": "helix-studios-vs-twinks-in-shorts",
    "siteA": "helix-studios",
    "siteB": "twinks-in-shorts",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "twinks-in-shorts",
    "priority": 4
  },
  {
    "slug": "athletic-twinks-vs-helix-studios",
    "siteA": "athletic-twinks",
    "siteB": "helix-studios",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "athletic-twinks",
    "priority": 4
  },
  {
    "slug": "helix-studios-vs-southern-strokes",
    "siteA": "helix-studios",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "southern-strokes",
    "priority": 4
  },
  {
    "slug": "boyfun-vs-helix-studios",
    "siteA": "boyfun",
    "siteB": "helix-studios",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "boyfun",
    "priority": 4
  },
  {
    "slug": "helix-studios-vs-touch-that-boy",
    "siteA": "helix-studios",
    "siteB": "touch-that-boy",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "touch-that-boy",
    "priority": 4
  },
  {
    "slug": "boysatcamp-vs-helix-studios",
    "siteA": "boysatcamp",
    "siteB": "helix-studios",
    "primaryNiche": "twink",
    "suggestedWinner": "helix-studios",
    "suggestedRunnerUp": "boysatcamp",
    "priority": 4
  },
  {
    "slug": "nakedsword-vs-rawhole",
    "siteA": "nakedsword",
    "siteB": "rawhole",
    "primaryNiche": "bareback",
    "suggestedWinner": "nakedsword",
    "suggestedRunnerUp": "rawhole",
    "priority": 4
  },
  {
    "slug": "southern-strokes-vs-twinks-in-shorts",
    "siteA": "southern-strokes",
    "siteB": "twinks-in-shorts",
    "primaryNiche": "twink",
    "suggestedWinner": "twinks-in-shorts",
    "suggestedRunnerUp": "southern-strokes",
    "priority": 4
  },
  {
    "slug": "boyfun-vs-twinks-in-shorts",
    "siteA": "boyfun",
    "siteB": "twinks-in-shorts",
    "primaryNiche": "twink",
    "suggestedWinner": "twinks-in-shorts",
    "suggestedRunnerUp": "boyfun",
    "priority": 4
  },
  {
    "slug": "touch-that-boy-vs-twinks-in-shorts",
    "siteA": "touch-that-boy",
    "siteB": "twinks-in-shorts",
    "primaryNiche": "twink",
    "suggestedWinner": "twinks-in-shorts",
    "suggestedRunnerUp": "touch-that-boy",
    "priority": 4
  },
  {
    "slug": "boysatcamp-vs-twinks-in-shorts",
    "siteA": "boysatcamp",
    "siteB": "twinks-in-shorts",
    "primaryNiche": "twink",
    "suggestedWinner": "twinks-in-shorts",
    "suggestedRunnerUp": "boysatcamp",
    "priority": 4
  },
  {
    "slug": "peterfever-vs-yoshikawasakixxx",
    "siteA": "peterfever",
    "siteB": "yoshikawasakixxx",
    "primaryNiche": "asian",
    "suggestedWinner": "peterfever",
    "suggestedRunnerUp": "yoshikawasakixxx",
    "priority": 4
  },
  {
    "slug": "familydick-vs-sayuncle",
    "siteA": "familydick",
    "siteB": "sayuncle",
    "primaryNiche": "daddy",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "familydick",
    "priority": 4
  },
  {
    "slug": "daddy-on-twink-vs-sayuncle",
    "siteA": "daddy-on-twink",
    "siteB": "sayuncle",
    "primaryNiche": "daddy",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "daddy-on-twink",
    "priority": 4
  },
  {
    "slug": "sayuncle-vs-twinktrade",
    "siteA": "sayuncle",
    "siteB": "twinktrade",
    "primaryNiche": "twink",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "twinktrade",
    "priority": 4
  },
  {
    "slug": "brothercrush-vs-sayuncle",
    "siteA": "brothercrush",
    "siteB": "sayuncle",
    "primaryNiche": "twink",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "brothercrush",
    "priority": 4
  },
  {
    "slug": "missionaryboys-vs-sayuncle",
    "siteA": "missionaryboys",
    "siteB": "sayuncle",
    "primaryNiche": "twink",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "missionaryboys",
    "priority": 4
  },
  {
    "slug": "sayuncle-vs-trailertrashboys",
    "siteA": "sayuncle",
    "siteB": "trailertrashboys",
    "primaryNiche": "str8-curious",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "trailertrashboys",
    "priority": 4
  },
  {
    "slug": "dadcreep-vs-sayuncle",
    "siteA": "dadcreep",
    "siteB": "sayuncle",
    "primaryNiche": "daddy",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "dadcreep",
    "priority": 4
  },
  {
    "slug": "sayuncle-vs-yesfather",
    "siteA": "sayuncle",
    "siteB": "yesfather",
    "primaryNiche": "daddy",
    "suggestedWinner": "sayuncle",
    "suggestedRunnerUp": "yesfather",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-southern-strokes",
    "siteA": "gayasiannetwork",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "southern-strokes",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-japanboyz",
    "siteA": "gayasiannetwork",
    "siteB": "japanboyz",
    "primaryNiche": "asian",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "japanboyz",
    "priority": 4
  },
  {
    "slug": "boyfun-vs-gayasiannetwork",
    "siteA": "boyfun",
    "siteB": "gayasiannetwork",
    "primaryNiche": "twink",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "boyfun",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-touch-that-boy",
    "siteA": "gayasiannetwork",
    "siteB": "touch-that-boy",
    "primaryNiche": "twink",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "touch-that-boy",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-rawhole",
    "siteA": "gayasiannetwork",
    "siteB": "rawhole",
    "primaryNiche": "bareback",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "rawhole",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-trailertrashboys",
    "siteA": "gayasiannetwork",
    "siteB": "trailertrashboys",
    "primaryNiche": "amateur",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "trailertrashboys",
    "priority": 4
  },
  {
    "slug": "gayasiannetwork-vs-sexjapantv",
    "siteA": "gayasiannetwork",
    "siteB": "sexjapantv",
    "primaryNiche": "asian",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "sexjapantv",
    "priority": 4
  },
  {
    "slug": "aussiesdoit-vs-gayasiannetwork",
    "siteA": "aussiesdoit",
    "siteB": "gayasiannetwork",
    "primaryNiche": "amateur",
    "suggestedWinner": "gayasiannetwork",
    "suggestedRunnerUp": "aussiesdoit",
    "priority": 4
  },
  {
    "slug": "japanboyz-vs-yoshikawasakixxx",
    "siteA": "japanboyz",
    "siteB": "yoshikawasakixxx",
    "primaryNiche": "japanese",
    "suggestedWinner": "yoshikawasakixxx",
    "suggestedRunnerUp": "japanboyz",
    "priority": 4
  },
  {
    "slug": "daddy-on-twink-vs-familydick",
    "siteA": "daddy-on-twink",
    "siteB": "familydick",
    "primaryNiche": "daddy",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "daddy-on-twink",
    "priority": 4
  },
  {
    "slug": "familydick-vs-twinktrade",
    "siteA": "familydick",
    "siteB": "twinktrade",
    "primaryNiche": "twink",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "twinktrade",
    "priority": 4
  },
  {
    "slug": "brothercrush-vs-familydick",
    "siteA": "brothercrush",
    "siteB": "familydick",
    "primaryNiche": "twink",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "brothercrush",
    "priority": 4
  },
  {
    "slug": "familydick-vs-missionaryboys",
    "siteA": "familydick",
    "siteB": "missionaryboys",
    "primaryNiche": "twink",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "missionaryboys",
    "priority": 4
  },
  {
    "slug": "familydick-vs-trailertrashboys",
    "siteA": "familydick",
    "siteB": "trailertrashboys",
    "primaryNiche": "str8-curious",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "trailertrashboys",
    "priority": 4
  },
  {
    "slug": "dadcreep-vs-familydick",
    "siteA": "dadcreep",
    "siteB": "familydick",
    "primaryNiche": "daddy",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "dadcreep",
    "priority": 4
  },
  {
    "slug": "familydick-vs-yesfather",
    "siteA": "familydick",
    "siteB": "yesfather",
    "primaryNiche": "daddy",
    "suggestedWinner": "familydick",
    "suggestedRunnerUp": "yesfather",
    "priority": 4
  },
  {
    "slug": "southern-strokes-vs-twinktrade",
    "siteA": "southern-strokes",
    "siteB": "twinktrade",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "twinktrade",
    "priority": 4
  },
  {
    "slug": "brothercrush-vs-southern-strokes",
    "siteA": "brothercrush",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "brothercrush",
    "priority": 4
  },
  {
    "slug": "missionaryboys-vs-southern-strokes",
    "siteA": "missionaryboys",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "missionaryboys",
    "priority": 4
  },
  {
    "slug": "boyfun-vs-southern-strokes",
    "siteA": "boyfun",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "boyfun",
    "priority": 4
  },
  {
    "slug": "southern-strokes-vs-touch-that-boy",
    "siteA": "southern-strokes",
    "siteB": "touch-that-boy",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "touch-that-boy",
    "priority": 4
  },
  {
    "slug": "rawhole-vs-southern-strokes",
    "siteA": "rawhole",
    "siteB": "southern-strokes",
    "primaryNiche": "bareback",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "rawhole",
    "priority": 4
  },
  {
    "slug": "southern-strokes-vs-trailertrashboys",
    "siteA": "southern-strokes",
    "siteB": "trailertrashboys",
    "primaryNiche": "amateur",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "trailertrashboys",
    "priority": 4
  },
  {
    "slug": "aussiesdoit-vs-southern-strokes",
    "siteA": "aussiesdoit",
    "siteB": "southern-strokes",
    "primaryNiche": "amateur",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "aussiesdoit",
    "priority": 4
  },
  {
    "slug": "boysatcamp-vs-southern-strokes",
    "siteA": "boysatcamp",
    "siteB": "southern-strokes",
    "primaryNiche": "twink",
    "suggestedWinner": "southern-strokes",
    "suggestedRunnerUp": "boysatcamp",
    "priority": 4
  },
  {
    "slug": "dadcreep-vs-daddy-on-twink",
    "siteA": "dadcreep",
    "siteB": "daddy-on-twink",
    "primaryNiche": "daddy",
    "suggestedWinner": "daddy-on-twink",
    "suggestedRunnerUp": "dadcreep",
    "priority": 4
  },
  {
    "slug": "daddy-on-twink-vs-yesfather",
    "siteA": "daddy-on-twink",
    "siteB": "yesfather",
    "primaryNiche": "daddy",
    "suggestedWinner": "daddy-on-twink",
    "suggestedRunnerUp": "yesfather",
    "priority": 4
  }
];

export const getComparisonPair = (slug: string): ComparisonPair | undefined =>
  comparisonPairs.find((p) => p.slug === slug);

export const getComparisonsByNiche = (nicheSlug: string): ComparisonPair[] =>
  comparisonPairs.filter((p) => p.primaryNiche === nicheSlug);

export const getPopularComparisons = (count: number = 6): ComparisonPair[] =>
  [...comparisonPairs]
    .sort((a, b) => b.priority - a.priority)
    .slice(0, count);
